//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPlatForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipAddress
    {
        public int id { get; set; }
        public string loginIP { get; set; }
        public string loginUser { get; set; }
        public System.DateTime loginTime { get; set; }
        public string loginWebsite { get; set; }
        public string loginCountry { get; set; }
        public string loginProvince { get; set; }
        public string loginCity { get; set; }
    }
}
