//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPlatForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiShiBet
    {
        public int betId { get; set; }
        public string userName { get; set; }
        public decimal amount { get; set; }
        public decimal betUnit { get; set; }
        public string betNumber { get; set; }
        public int playType { get; set; }
        public int lotteryType { get; set; }
        public System.DateTime betTime { get; set; }
        public decimal betIssue { get; set; }
        public string serialNumber { get; set; }
        public int status { get; set; }
        public decimal prize { get; set; }
        public string position { get; set; }
        public int returnRate { get; set; }
    }
}
